name: MinecraftManhuntPlugin
version: 1.0
main: com.github.ricetech.minecraftmanhuntplugin.MinecraftManhuntPlugin
api-version: 1.16
author: the_ricetech
authors:
  - jonapap
  - OrangeFirefly
commands:
  countdown:
    description: Starts a simple countdown timer. Useful for giving speedrunners a head start in Manhunt.
    usage: /countdown <time in seconds>
  rs:
    description: Resets the state of the world and players to prepare for a new game.
    usage: /rs
  changeteam:
    description: Change to another team or join a team if not already part of one.
    usage: /changeteam <runners|eliminated|hunters|spectators>
  newgame:
    description: Start a new game.
    usage: /newgame
  startgame:
    description: Resets all players and starts a new game with a countdown timer.
    usage: /startgame <time in seconds>
  stopgame:
    description: Stops a manhunt game in progress.
    usage: /stopgame
  selfelim:
    description: Eliminate yourself from the game. Only works if you are a runner.
    usage: /selfelim