name: MinecraftManhuntPlugin
description: Play Manhunt on your Spigot/Paper Minecraft server!
version: 1.0.1
main: com.github.ricetech.minecraftmanhuntplugin.MinecraftManhuntPlugin
api-version: 1.18
author: the_ricetech
authors:
  - jonapap
  - OrangeFirefly
website: https://github.com/ricetech/MinecraftManhuntPlugin
commands:
  # Game Management
  clearteams:
    description: Remove all players from all teams.
    usage: "Usage: /clearteams"
    permission: mmh.game
  maketeams:
    description: >
      Generate teams for a new game. If provided, the "random" argument will randomize the teams. Otherwise, the default if no argument
      is provided allows each player to select their team.
    usage: "Usage: /maketeams [random|select]"
    permission: mmh.game
  startgame:
    description: >
      Resets all players and starts a new game with a countdown timer.
      Set the optional second option to 'true' if you do not want to reset all players.
      Set the optional third option to 'true' if you do not want to freeze & reset all hunters.
    usage: "Usage: /startgame <time in seconds> [(don't reset) true|false] [(don't freeze/reset Hunters) true|false]"
    permission: mmh.game
  stopgame:
    description: Stops a manhunt game in progress.
    usage: "Usage: /stopgame"
    permission: mmh.game
  # Utilities
  countdown:
    description: >
      Starts a simple countdown timer. Useful for giving speedrunners a head start in Manhunt.
      If the optional second argument is true, the Hunters will be frozen in place and sent back to spawn post-countdown.
    usage: "Usage: /countdown <time in seconds> [(freeze/reset Hunters) true|false]"
    permission: mmh.player
  reset:
    description: Resets the state of the world and players to prepare for a new game.
    usage: "Usage: /reset"
    permission: mmh.player
  manhuntversion:
    description: Shows the version and website of this plugin.
    usage: "Usage: /manhuntversion"
    permission: mmh.player
  # Player
  listteams:
    description: List the teams and the players on each team.
    usage: "Usage: /listteams"
    permission: mmh.player
  track:
    description: Track a player using a compass.
    usage: "Usage: /track <player>"
    permission: mmh.player
  trackportal:
    description: Track the portal you used to enter The Nether.
    usage: "Usage: /trackportal"
    permission: mmh.player
  # Operator commands
  creditkill:
    description: >
      Credit a kill to another player. Useful if the game says a player died to natural causes even if another player
      killed them.
    usage: "Usage: /creditkill <player>"
    permission: mmh.correction
  eliminate:
    description: Eliminate a player. For use if the game didn't eliminate them automatically. Also kills the player.
    usage: "Usage: /eliminate <eliminated player> <player who is eliminating/killing the other player>"
    permission: mmh.correction
  offerteamtp:
    description: >
      Offer the list of teammates to teleport to (or death location if no teammates are available) to a player.
      Replaces the menu normally provided if a player states they died to natural causes.
    usage: "Usage: /offerteamtp <player>"
    permission: mmh.correction
  removedeath:
    description: >
      Remove a death from a player's Death counter.
    usage: "Usage: /removedeath <player>"
    permission: mmh.correction
  restoreinventory:
    description: >
      Offer a player's previous inventory (stored at the point where they died) to the player to allow them to
      select items to restore.
    usage: "Usage: /restoreinventory <player>"
    permission: mmh.correction
  setplayerteam:
    description: Forcibly change a player's team, whether they are eligible to switch or not.
    usage: "Usage: /setplayerteam <player> <runners|eliminated|hunters|spectators>"
    permission: mmh.correction
  uneliminate:
    description: Un-eliminate a player. Restores them to the Runners team.
    usage: "Usage: /uneliminate <eliminated player>"
    permission: mmh.correction
  # Internal use
  changeteam:
    description: Internal use only.
    usage: "Usage: /changeteam <runners|eliminated|hunters|spectators>"
    permission: mmh.player
  reseteligibility:
    description: Internal use only.
    usage: "Usage: /reseteligibility"
    permission: mmh.player
  selfelim:
    description: Internal use only.
    usage: "Usage: /selfelim"
    permission: mmh.player
  teamtp:
    description: Internal use only.
    usage: "Usage: /teamtp <target player>"
    permission: mmh.player
  tpoptions:
    description: Internal use only.
    usage: "Usage: /tpoptions"
    permission: mmh.player
permissions:
  mmh.player:
    description: Gives access to commands used by players and spectators.
    default: true
  mmh.game:
    description: Gives access to commands used to start/stop the game.
    default: true
  mmh.correction:
    description: >
      Gives access to commands used to correct game errors such as a player on the wrong team,
      a player eliminated wrongly, or a player that did not get eliminated when they should have been.
    default: op